CREATE DATABASE DockerfileDB; DEFAULT CHARACTER SET utf8;
CREATE USER yck@localhost IDENTIFIED BY '103099@qet';
USE DockerfileDB;
GRANT ALL PRIVILEGES ON wordpress.* yck@localhost IDENTIFIED BY '103099@qet';
FLUSH PRIVILEGES;

